### ISSUE TITLE
Machine Side Control Electronics Mounting

### ISSUE THREAD

**Issue by ttsgeb** [chattlab-makerspace/LF-CNC-Router#2]
Location and mounting needs to determined for

VFD
Contactor
Relay

**Comment by lawnchairsociety** [comment]
We made a mounting panel for VFD, Contactors (2), and Relay. Need M4 x 20 screws (at least 6) to mount hardware to panel

**Comment by ttsgeb** [comment]
We made a lot of progress tonight on planning for how this will go together and getting things laid out for putting it together.
I drew some sketches of the wiring plan for the 24VDC and 240VAC systems.  They're with the appropriate parts, however @lawnchairsociety got photos of them as well.  Would be cool to drop them here so that we can all be a bit closer to being on the same page.

**Comment by lawnchairsociety** [comment]
I picked up 6 M4x20 cap head screws and 2 M4 washers this morning. I'll see about mounting the equipment to the control panel.

**Comment by lawnchairsociety** [comment]
Attached DIN rail and VFD to control panel with M4 hardware

**Comment by ttsgeb** [comment]
Machine side wiring is functionally complete.
