### ISSUE TITLE
Y-Axis Refurb

### ISSUE THREAD

**Issue by ttsgeb** [chattlab-makerspace/LF-CNC-Router#3]
Large amounts of slop and backlash in Y axis need to be addressed

Remove Motors (right side harness will need to be cut, left side has a disconnect)
Move Gantry to far side of machine (Operator's Perspective)
Remove Bearing blocks 1 at a time
Rebuild Bearings
Pre-Tension Bearings on rail
Loosely reinstall Bearings
Carefully run gantry over length of machine while maintaining square with work table
Tighten Bearing Installation
Set engagement on gear reductions
Install disconnect to right side motor harness
Install motors
Set engagement between motor and gear reduction
Testing

**Comment by lawnchairsociety** [comment]
`Install disconnect to right side motor harness` - This is the wiring aspect of this issue

**Comment by ttsgeb** [comment]
While working on the refurb, bearings fell completely apart. This is being addressed in #9 .

**Comment by ttsgeb** [comment]
This rebuild was completed successfully.
